# Generated by Django 3.2 on 2024-03-25 12:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('saved_viewings', '0010_remove_country'),
        ('accounts', '0001_profile'),
    ]

    operations = [
        migrations.AddField(
            model_name='country',
            name='streams',
            field=models.ManyToManyField(related_name='countries', to='saved_viewings.StreamingService'),
        ),
        migrations.AddField(
            model_name='profile',
            name='streams',
            field=models.ManyToManyField(related_name='Profiles', to='saved_viewings.StreamingService'),
        ),
    ]
