# Generated by Django 3.2.23 on 2024-02-05 17:38

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('saved_viewings', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='MovieOrShow',
            fields=[
                ('title_id', models.IntegerField(max_length=30, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField(null=True)),
                ('tmdb_rating', models.FloatField(null=True)),
                ('type', models.IntegerField(choices=[(0, 'Movie'), (1, 'TV-Show')], default=0)),
                ('year', models.IntegerField(null=True)),
                ('runtime', models.IntegerField(null=True)),
                ('seasons', models.IntegerField(null=True)),
                ('age_limit', models.CharField(max_length=30)),
                ('poster_link', models.URLField()),
                ('backdrop_link', models.URLField()),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='blog_posts', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.DeleteModel(
            name='Movie_Or_Show',
        ),
    ]
