# Generated by Django 3.2.23 on 2024-02-05 17:56

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('saved_viewings', '0002_auto_20240205_1738'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movieorshow',
            name='title_id',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='movieorshow',
            name='user_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='viewings', to=settings.AUTH_USER_MODEL),
        ),
    ]
