# Generated by Django 3.2.23 on 2024-02-11 15:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('saved_viewings', '0002_movie_or_show'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='movieorshow',
            name='year',
        ),
        migrations.AddField(
            model_name='movieorshow',
            name='date',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='movieorshow',
            name='is_in_dont_show',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='movieorshow',
            name='is_in_favourites',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='movieorshow',
            name='is_in_roulette',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='movieorshow',
            name='is_in_seen_it',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='movieorshow',
            name='is_in_watchlist',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='movieorshow',
            name='age_limit',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='movieorshow',
            name='backdrop_link',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='movieorshow',
            name='poster_link',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='movieorshow',
            name='runtime',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='movieorshow',
            name='seasons',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
