# Generated by Django 3.2.23 on 2024-02-17 22:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('saved_viewings', '0003_update_movie_or_show'),
    ]

    operations = [
        migrations.CreateModel(
            name='Genre',
            fields=[
                ('genre_id', models.IntegerField(primary_key=True, serialize=False, unique=True)),
                ('name', models.CharField(blank=True, max_length=50, null=True)),
            ],
        ),
    ]
