# Generated by Django 3.2.23 on 2024-02-29 11:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('saved_viewings', '0004_add_genre'),
    ]

    operations = [
        migrations.AddField(
            model_name='movieorshow',
            name='status',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
    ]
