# Generated by Django 3.2.23 on 2024-02-29 11:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('saved_viewings', '0005_add_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='TitleGenre',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('genre_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='genre', to='saved_viewings.genre')),
                ('title_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='title_genre', to='saved_viewings.movieorshow')),
            ],
        ),
    ]
