# Generated by Django 3.2.23 on 2024-02-29 19:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('saved_viewings', '0006_update_genre'),
    ]

    operations = [
        migrations.CreateModel(
            name='Person',
            fields=[
                ('person_id', models.IntegerField(primary_key=True, serialize=False, unique=True)),
                ('full_name', models.CharField(blank=True, max_length=200, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Director',
            fields=[
                ('director_id', models.IntegerField(primary_key=True, serialize=False, unique=True)),
                ('people', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='saved_viewings.person')),
                ('titles', models.ManyToManyField(related_name='directors', to='saved_viewings.MovieOrShow')),
            ],
        ),
        migrations.CreateModel(
            name='Creator',
            fields=[
                ('creator_id', models.IntegerField(primary_key=True, serialize=False, unique=True)),
                ('people', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='saved_viewings.person')),
                ('titles', models.ManyToManyField(related_name='creators', to='saved_viewings.MovieOrShow')),
            ],
        ),
        migrations.CreateModel(
            name='Actor',
            fields=[
                ('actor_id', models.IntegerField(primary_key=True, serialize=False, unique=True)),
                ('people', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='saved_viewings.person')),
                ('titles', models.ManyToManyField(related_name='actors', to='saved_viewings.MovieOrShow')),
            ],
        ),
    ]
