# Generated by Django 3.2.23 on 2024-03-02 11:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('saved_viewings', '0007_cast_and_crew_model'),
    ]

    operations = [
        migrations.CreateModel(
            name='Country',
            fields=[
                ('country_iso', models.CharField(max_length=50, primary_key=True, serialize=False, unique=True)),
                ('name', models.CharField(blank=True, max_length=50, null=True)),
            ],
        ),
    ]
