# Generated by Django 3.2.23 on 2024-03-02 12:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('saved_viewings', '0008_country_model'),
    ]

    operations = [
        migrations.CreateModel(
            name='StreamingService',
            fields=[
                ('provider_id', models.IntegerField(primary_key=True, serialize=False, unique=True)),
                ('name', models.CharField(blank=True, max_length=200, null=True)),
                ('logo_path', models.CharField(blank=True, max_length=200, null=True)),
                ('of_title', models.ManyToManyField(related_name='streaming_services', to='saved_viewings.MovieOrShow')),
            ],
        ),
    ]
