# Generated by Django 3.2.23 on 2024-03-10 22:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('saved_viewings', '0009_streaming_service__model'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Country',
        ),
    ]
