# Generated by Django 3.2 on 2024-03-31 19:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('saved_viewings', '0010_remove_country'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='actor',
            name='titles',
        ),
        migrations.RemoveField(
            model_name='creator',
            name='titles',
        ),
        migrations.RemoveField(
            model_name='director',
            name='titles',
        ),
        migrations.RemoveField(
            model_name='genre',
            name='titles',
        ),
        migrations.RemoveField(
            model_name='streamingservice',
            name='of_title',
        ),
        migrations.DeleteModel(
            name='MovieOrShow',
        ),
    ]
